version: "3"
services:
  springboot-app:
    container_name: achat-app
    image: wissemhammouda/alpine:2.1-SPRING-COMPOSE
    restart: always
    build: .
    ports:
      - 8000-8999:8089
    environment:
      MYSQL_HOST: mysqldb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_PORT: 3306
  mysqldb:
    container_name: mysqldbachat
    image: mysql
   # volumes:
      #-  /home/user/5SE2/DEVOPS/Projet/db:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: root
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    environment:
      PMA_HOST: mysqldb
      PMA_PORT: 3306
    ports:
      - "8080:80"
